/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include"GPIO_Driver.h"

int main(void)
{
	// 1. Enable GPIOA clock
	    GPIO_Clockcontrol(GPIOA, ENABLE);

	    // 2. Configure PA5 as output
	    GPIO_Init_t GPIO_Pin;
	    GPIO_Pin.GPIO_PinNumber      = 3;    // Pin number
	    GPIO_Pin.GPIO_PinMode        = GPIO_MODE_OUT;    // Output mode
	    GPIO_Pin.GPIO_PinOPType      = 1;    // Push-pull
	    GPIO_Pin.GPIO_PinSpeed       = GPIO_SPEED_HIGH;    // Medium speed
	    GPIO_Pin.GPIO_PinPuPdControl = GPIO_PIN_PU;    // No pull-up/pull-down
	    GPIO_Pin.GPIO_PinAltFunMode  = GPIO_AF1;    // Not used for output

	    // 3. Initialize PA5
	    GPIO_Init(GPIOA, &GPIO_Pin);
    /* Loop forever */
	for(;;);
}
