/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include"GPIO_Driver.h"

int main(void)
{
    GPIO_Clockcontrol(GPIOC, ENABLE);

    GPIO_Init_t GPIO_Pin;
    GPIO_Pin.GPIO_PinNumber = 13;
    GPIO_Pin.GPIO_PinMode = GPIO_MODE_OUT;
    GPIO_Pin.GPIO_PinOPType = GPIO_OP_TYPE_PP;
    GPIO_Pin.GPIO_PinSpeed = GPIO_SPEED_LOW;
    GPIO_Pin.GPIO_PinPuPdControl = GPIO_NO_PUPD;

    GPIO_Init(GPIOC, &GPIO_Pin);

    while(1)
    {
        GPIO_ToggleOutputPin(GPIOC, 13);

        for(int i = 0; i < 50000; i++);
    }
}
